"""initial_phase1_schema

Revision ID: 822038d85abc
Revises: 
Create Date: 2026-10-08 22:53:15.801699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822038d85abc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_task_type'), ['task_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('candidate_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_facts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_facts_user_id'), ['user_id'], unique=False)

    op.create_table('career_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('target_job_titles', sa.JSON(), nullable=False),
    sa.Column('technical_skills', sa.JSON(), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('preferred_locations', sa.JSON(), nullable=False),
    sa.Column('work_preference', sa.JSON(), nullable=False),
    sa.Column('employment_type', sa.JSON(), nullable=False),
    sa.Column('salary_expectation', sa.JSON(), nullable=False),
    sa.Column('excluded_companies', sa.JSON(), nullable=False),
    sa.Column('matching_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_type', name='uq_user_profile_type')
    )
    with op.batch_alter_table('career_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_profiles_profile_type'), ['profile_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('work_mode', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_canonical_hash'), ['canonical_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_title'), ['title'], unique=False)

    op.create_table('job_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('required_skills_score', sa.Integer(), nullable=False),
    sa.Column('experience_score', sa.Integer(), nullable=False),
    sa.Column('alignment_score', sa.Integer(), nullable=False),
    sa.Column('preferences_score', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('match_evidence', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_job_profile_match')
    )
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_matches_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_profile_id'), ['profile_id'], unique=False)

    op.create_table('profile_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('relevance_weight', sa.Float(), nullable=False),
    sa.Column('is_highlighted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['candidate_facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'fact_id', name='uq_profile_fact')
    )
    with op.batch_alter_table('profile_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_facts_fact_id'), ['fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_facts_profile_id'), ['profile_id'], unique=False)

    op.create_table('resume_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('version_name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('selected_facts', sa.JSON(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('pdf_storage_path', sa.String(length=512), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_versions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_versions_profile_id'), ['profile_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('resume_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submission_method', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_application')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_profile_id'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_versions_profile_id'))
        batch_op.drop_index(batch_op.f('ix_resume_versions_job_id'))

    op.drop_table('resume_versions')
    with op.batch_alter_table('profile_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_facts_profile_id'))
        batch_op.drop_index(batch_op.f('ix_profile_facts_fact_id'))

    op.drop_table('profile_facts')
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_matches_profile_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_job_id'))

    op.drop_table('job_matches')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_company'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_hash'))

    op.drop_table('jobs')
    with op.batch_alter_table('career_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_career_profiles_profile_type'))

    op.drop_table('career_profiles')
    with op.batch_alter_table('candidate_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_facts_user_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_facts_category'))

    op.drop_table('candidate_facts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_runs_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_runs_status'))

    op.drop_table('task_runs')
    op.drop_table('job_sources')
    # ### end Alembic commands ###
